[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
LOG_LEVEL = "INFO"
CORS_ORIGINS = "https://attack-a-litics.vercel.app,https://attack-a-litics-*.vercel.app"